---
version: 3

images:
  base_image:
    name: 'minimal-decision-environment:latest'
dependencies:
  galaxy: requirements.yml
  system: bindep.txt
additional_build_steps:
  prepend_base: |
    RUN wget https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_linux_amd64 -O /usr/local/bin/yq && chmod +x /usr/local/bin/yq
  append_final:
    - 'RUN mkdir -p /opt/ansible'
    - 'ADD playbooks /opt/ansible/playbooks'
    - 'ADD rulebook.yml inventory /opt/ansible/'
options:
  container_init:
    cmd: '["/opt/builder/bin/entrypoint","ansible-rulebook", "--rulebook", "/opt/ansible/rulebook.yml", "-i", "/opt/ansible/inventory", "--print-events"]'
