---

- name: Listen for events
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 8080


  rules:

    - name: "Demo"
      condition: event.payload.playbook == 'demo' and event.payload.task == 'say_hello'
      action:
        run_playbook:
          name: /opt/ansible/playbooks/demo/say_hello.yml
